production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    timeout: 1
    open_timeout: 1
  auto_index_callback: after_commit
  auto_remove_callback: after_commit

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/development
    timeout: 1
    open_timeout: 1
  auto_index_callback: after_commit
  auto_remove_callback: after_commit

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
    timeout: 1
    open_timeout: 1
  auto_index_callback: after_commit
  auto_remove_callback: after_commit
